### ISSUE TITLE
My profile

### ISSUE THREAD

**Issue by 4us1on** [Adrriii/osudaily#11]
So I connected my account to the website and showed no information. Says that the account was fresh and was never played. Is there a way to fix this issue? thank you
![my profile](https://user-images.githubusercontent.com/130818860/232184961-aba259e8-44d0-45ea-94f7-c5c5d317ef58.png)

**Comment by Bullfrog098** [comment]
This is because you just signed up, there is no data yet. After some time data will start being added and you'll be able to see it. Keep in mind any thing before hand will not be there as you weren't signed up yet

**Comment by Adrriii** [comment]
> This is because you just signed up, there is no data yet. After some time data will start being added and you'll be able to see it. Keep in mind any thing before hand will not be there as you weren't signed up yet

Exactly, thanks :)
