### ISSUE TITLE
Settings page doesn't show up / doesn't contain content

### ISSUE THREAD

**Issue by Fiabilandia** [Adrriii/osudaily#13]
I've experienced a specific problem for longer time. Namely the settings page doesn't show up any content when i navigate to it. There is only the footer content displayed but even that is cut off and the whole page / tab seems broken. I tried to open the settings on my mobile phone and there's the exact same problem. Also i tried changing to different browsers and turning off extensions, ad-blockers, etc.

Is there some way to fix this issue or do i have to abstain from accessing my settings?

Screenshot below shows the issue in Chrome (Desktop Version)

![image](https://github.com/Adrriii/osudaily/assets/147161128/61d35fd1-932b-4bcb-9c4d-09cbb7614029)

**Comment by Fiabilandia** [comment]
I've also thought, that the problem could be hardware-related as some things are generally displayed incorrectly on my 6 yrs old PC-Build  but i opened this issue ticket to see also if other people got a similar issue or if it could be a Web-Browser Error after all.

**Comment by Adrriii** [comment]
There is something wrong indeed, I will look whenever i can.

**Comment by Fiabilandia** [comment]
Thanks. i appreciate it!
