### ISSUE TITLE
Taiko PP browser

### ISSUE THREAD

**Issue by WinterIsPretty** [Adrriii/osudaily#5]
The taiko pp browser isn't correct anymore maybe because of the pp balance that happened like a month or 2 ago

**Comment by Adrriii** [comment]
Oh right, i'll see what i can do about this. Thank you for reporting

**Comment by Adrriii** [comment]
Added a script to clear old data from the table supposed to hold the latest data
Before and after on the pp vs rank graph :
![before](https://user-images.githubusercontent.com/16978299/101533411-167b7780-3996-11eb-818b-f7392de63f15.png)
![after](https://user-images.githubusercontent.com/16978299/101533415-17aca480-3996-11eb-9b6c-47eaf878bbee.png)

**Comment by WinterIsPretty** [comment]
ooooooooh so that's what that was, wow nice I'm glad that's fixed
