### ISSUE TITLE
Trying to register/login failed

### ISSUE THREAD

**Issue by byzocker** [Adrriii/osudaily#8]
i was just trying to login what happend 
![image](https://user-images.githubusercontent.com/59401089/133493024-23f136b7-a2ea-4920-86a8-e1cd44c9f216.png)

my osu username is - tobi -

**Comment by Adrriii** [comment]
Did this happen only once or more than once ? Does it still happen ?

**Comment by DanielPower** [comment]
This happened to me, and after re-trying it succeeded. But my profile has no data. 

https://osudaily.net/profile.php?u=25477

Level 0, 0 plays, etc. Is this normal? Does it just take time to populate with data?

**Comment by Adrriii** [comment]
Yes the profile is empty on sign-up. It's actually due to a bug related to the reported error, but it doesn't break the profile and it will successfully collect data every day.
